---
abstract: "add the author's pledge to the distribution"
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::DZil: '0'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Covenant
provides:
  Dist::Zilla::Plugin::Covenant:
    file: lib/Dist/Zilla/Plugin/Covenant.pm
    version: v0.1.1
requires:
  Dist::Zilla::File::InMemory: '0'
  Dist::Zilla::Role::FileGatherer: '0'
  Dist::Zilla::Role::MetaProvider: '0'
  Dist::Zilla::Role::Plugin: '0'
  Dist::Zilla::Role::TextTemplate: '0'
  Moose: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dist-Zilla-Plugin-Covenant/issues
  homepage: https://github.com/yanick/Dist-Zilla-Plugin-Covenant
  repository: https://github.com/yanick/Dist-Zilla-Plugin-Covenant.git
version: 0.1.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Apocalypse <APOCAL@cpan.org>'
