name: CI 
on:
  push:
    branches:
      - main 
      - releases 
  pull_request:
    branches: [ '**' ]

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - 'latest'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    name: Build on Linux with Perl ${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Install deps 
        run: |
          cpanm --installdeps . --notest

      - name: Run tests
        run: prove -l t
